# Site settings
title: XDG Desktop Portal
baseurl: "/xdg-desktop-portal-website" # the subpath of your site, e.g. /blog/
                                 # usually empty. necessary for building absolute URIs
                                 # for metadata header
url: "https://jimmac.github.io"   # the base hostname & protocol for your site
sourceurl: "https://github.com/jimmac/xdg-desktop-portal-website" # "edit this website" link in the footer
description: ""
issuesurl: "https://github.com/jimmac/xdg-desktop-portal-website/issues" # issue tracker for website
permalink: /:title/
primary-color: "#26a269" #used in ios theme. further color customization in style.css  

# Build settings
markdown: kramdown
